---
driver:
  name: docker
  privileged: true
  run_command: "/usr/sbin/init"
  remove_images: false

provisioner:
  name: chef_solo

platforms:
  - name: fedora-20
    driver_config:
      dockerfile: test/Dockerfile.f20
  - name: fedora-22
    driver_config:
      dockerfile: test/Dockerfile.f22

suites:
- name: default
  run_list:
    - recipe[]
  attributes:
    kitchen: true
