---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: fedora-20
  - name: fedora-22
    attribute:
      kitchen: true
suites:
- name: install
  run_list:
    - recipe[dnf_package_install_test]
- name: upgrade
  run_list:
    - recipe[dnf_package_upgrade_test]
- name: remove
  run_list:
    - recipe[dnf_package_remove_test]
