---
driver:
  name: docker
  privileged: true
  run_command: "/usr/sbin/init"
  remove_images: false

provisioner:
  name: chef_solo

platforms:
<% %w(11.16.4 12.3.0 12.4.0).each do |chef_version| %>
  - name: fedora-22-chef-<%= chef_version %>
    driver_config:
      dockerfile: test/Dockerfile.f22
      attribute:
        kitchen: true
      require_chef_omnibus: <%= chef_version %>
<% end %>

suites:
- name: install
  run_list:
    - recipe[dnf_package_install_test]
- name: upgrade
  run_list:
    - recipe[dnf_package_upgrade_test]
- name: remove
  run_list:
    - recipe[dnf_package_remove_test]
- name: multi-package-install
  run_list:
    - recipe[dnf_multi_package_install_test]
- name: multi-package-remove
  run_list:
    - recipe[dnf_multi_package_remove_test]
