---
driver:
  name: vagrant

provisioner:
  name: chef_solo

platforms:
#  - name: fedora-20
  - name: fedora-22

suites:
- name: default
  run_list:
    - recipe[dnf_test]
  attributes:
    kitchen: true
- name: install
  run_list:
    - recipe[dnf_test::install]
  attribute:
    kitchen: true
